flowchart TD
    p0((Channel.fromPath))
    p1((Channel.fromPath))
    p2[mmseqs2:CREATE_DB]
    p3[mmseqs2:LINCLUST]
    p4[mmseqs2:CREATE_TSV]
    p5[fasta_families:EXPORT_REPS]
    p6([splitText])
    p7([map])
    p8([first])
    p9([first])
    p10([take])
    p11[fasta_families:CREATE_FAMILY_FA]
    p12[msa_hmm:MAFFT]
    p13[msa_hmm:HMMBUILD]
    p14([first])
    p15[msa_hmm:HMMSCAN]
    p16(( ))
    p17(( ))
    p18(( ))
    p19(( ))
    p20(( ))
    p0 -->|fastaFile| p2
    p1 -->|uniprot_sprot_fasta_path| p14
    p2 --> p3
    p3 --> p4
    p2 -->|mmseqsDB| p4
    p4 -->|clust_tsv| p5
    p5 --> p6
    p6 --> p7
    p7 -->|reps_ch| p10
    p4 -->|clust_tsv| p8
    p8 --> p11
    p0 -->|fastaFile| p9
    p9 --> p11
    p10 --> p11
    p11 -->|familyFile| p12
    p12 --> p13
    p13 --> p15
    p14 --> p15
    p15 --> p20
    p15 --> p19
    p15 --> p18
    p15 --> p17
    p15 --> p16
