flowchart TD
    p0((Channel.fromPath))
    p1((Channel.fromPath))
    p2((Channel.fromPath))
    p3([collect])
    p4([collect])
    p5[update_clusters:CREATEDB]
    p6[update_clusters:CLUSTERUPDATE]
    p7(( ))
    p8(( ))
    p0 -->|new_fasta_ch| p5
    p1 -->|old_db_ch| p3
    p2 -->|old_clu_ch| p4
    p3 -->|old_db_ch| p6
    p4 -->|old_clu_ch| p6
    p5 --> p6
    p6 --> p8
    p6 --> p7
