flowchart TD
    p0((Channel.fromPath))
    p1((Channel.fromPath))
    p2[initiate_proteins:CONCAT_FILES]
    p3[initiate_proteins:EXPORT_PROTEINS_CSV]
    p4(( ))
    p5[execute_clustering:CREATEDB]
    p6[execute_clustering:LINCLUST]
    p7[execute_clustering:CREATETSV]
    p8[execute_clustering:EXPORT_CLUSTERS_CSV]
    p9(( ))
    p10[create_families:EXPORT_REPS]
    p11[create_families:EXPORT_FAMILIES_CSV]
    p12(( ))
    p13([splitText])
    p14([map])
    p15([first])
    p16([first])
    p17([take])
    p18[create_families:CREATE_FAMILY_FA]
    p19([collect])
    p20[create_families:EXPORT_REPS_FA]
    p21[produce_unknown_models:MAFFT]
    p22[produce_unknown_models:HMMBUILD]
    p23[produce_known_models:MAFFT]
    p24[produce_known_models:HMMBUILD]
    p25(( ))
    p26((Channel.fromPath))
    p27[annotate_families:getTopDebugLines]
    p28[annotate_families:INTERPROSCAN]
    p29(( ))
    p30[annotate_families:EGGNOG_MAPPER]
    p31(( ))
    p32([first])
    p33[annotate_families:HMMSCAN]
    p34(( ))
    p35(( ))
    p36(( ))
    p37(( ))
    p38(( ))
    p0 -->|mgnify_fasta_file| p2
    p1 -->|uniprot_sprot_fasta_input_debug_file| p2
    p2 -->|fastaFile| p3
    p3 --> p4
    p2 -->|fastaFile| p5
    p5 --> p6
    p6 --> p7
    p5 -->|mmseqs_DB| p7
    p7 -->|clust_tsv| p8
    p8 --> p9
    p7 -->|clust_tsv| p10
    p10 --> p11
    p11 --> p12
    p10 --> p13
    p13 --> p14
    p14 -->|reps_ch| p17
    p7 -->|clust_tsv| p15
    p15 --> p18
    p2 -->|fastaFile| p16
    p16 --> p18
    p17 --> p18
    p18 -->|familyFile| p23
    p18 -->|familyFile| p19
    p19 --> p20
    p20 -->|unknown_reps_fasta| p27
    p18 -->|familyFile| p21
    p21 --> p22
    p22 -->|build_ch| p33
    p23 --> p24
    p24 --> p25
    p26 -->|uniprot_sprot_fasta_path| p32
    p27 --> p28
    p28 --> p29
    p27 -->|fasta_file| p30
    p30 --> p31
    p32 --> p33
    p33 --> p38
    p33 --> p37
    p33 --> p36
    p33 --> p35
    p33 -->|tblout_ch| p34
