---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "hhsuite_reformat"
description: reformats multiple sequence alignment files among various standards
keywords:
  - MSA
  - reformat
  - fasta
tools:
  - "hhsuite":
      description: "HH-suite3 for fast remote homology detection and deep protein annotation"
      homepage: "https://github.com/soedinglab/hh-suite"
      documentation: "https://github.com/soedinglab/hh-suite/wiki"
      tool_dev_url: "https://github.com/soedinglab/hh-suite"
      doi: "10.1371/journal.pone.0082138"
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - a3m:
      type: file
      description: Multiple sequence alignment file in a3m format
      pattern: "*.a3m"
  - hmm_db:
      type: directory
      description: Directory containing HH specific database files
      pattern: "*"
  - db_name:
      type: string
      description: Prefix of the database files in hmm_db folder (e.g. pfam)
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - hhr:
      type: file
      description: File containing the result hits of the MSA input against the database of HH hmm models
      pattern: "*.hhr"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@vagkaratzas"
