---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
name: "hhsuite_buildhhdb"
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - "bioconda::hhsuite=3.3.0"
