channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.2
  - bioconda::easel=0.49
  - pip
  - pip:
    - pandas==2.2.3
    - biopython==1.85
    - pyfastx==2.2.0
    - pyfamsa==0.5.3
    - pyhmmer==0.11.0
