channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.12.9
  - pip
  - pip:
    - pandas==2.2.3
    - biopython==1.85
    - pyfastx==2.2.0
    - pyfamsa==0.5.3.post1
    - pyhmmer==0.11.1
    - pytrimal==0.7.0
    - numpy==2.2.4
