channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::pyhmmer=0.11.1
  - conda-forge::numpy=2.3.2
  - conda-forge::pandas=2.3.2
  - conda-forge::python=3.13.5
  - pip
  - pip:
    - biopython==1.85
    - pyfamsa==0.6.0
    - pytrimal==0.8.2
