flowchart TB
    subgraph " "
    v0["Channel.fromPath"]
    v2["Channel.fromPath"]
    v4["informat"]
    v5["outformat"]
    v9["informat"]
    v10["outformat"]
    v15["informat"]
    v16["outformat"]
    v19["hmm_db"]
    v20["db_name"]
    v29["compute_mode"]
    v54[" "]
    end
    subgraph REFORMAT_SEED_MSA
    v6([HHSUITE_REFORMAT])
    v8([TRANSLATE_MSA_MGYPS])
    v1(( ))
    end
    subgraph " "
    v7[" "]
    v12[" "]
    v14["fa_ch"]
    v18[" "]
    v22[" "]
    v24[" "]
    v25["pfam_hits"]
    v31[" "]
    v40[" "]
    v43[" "]
    v46["scores_ch"]
    v49[" "]
    v56[" "]
    v62[" "]
    end
    subgraph REFORMAT_HMMALIGN_MSA
    v11([HHSUITE_REFORMAT])
    v13([TRANSLATE_MSA_MGYPS])
    v3(( ))
    end
    subgraph ANNOTATE_MODELS
    v17([HHSUITE_REFORMAT])
    v21([HHSUITE_HHBLITS])
    v23([FILTER_HH_RESULTS])
    end
    subgraph PREDICT_STRUCTURES
    v26([EXTRACT_FIRST_STOCKHOLM_SEQUENCES_FROM_FOLDER])
    v30([ESMFOLD])
    v36([EXTRACT_LONG_FA])
    v39([ESMFOLD_CPU])
    v42([EXTRACT_ESMFOLD_SCORES])
    v48([PARSE_CIF])
    v27(( ))
    v33(( ))
    v37(( ))
    v41(( ))
    v44(( ))
    v47(( ))
    end
    subgraph ANNOTATE_STRUCTURES
    v55([FOLDSEEK_EASYSEARCH_PDB])
    v61([FIND_ANNOTATED_FAMILIES_BY_STRUCTURE])
    v57(( ))
    end
    v0 --> v1
    v2 --> v3
    v4 --> v6
    v5 --> v6
    v1 --> v6
    v6 --> v8
    v6 --> v7
    v8 --> v17
    v9 --> v11
    v10 --> v11
    v3 --> v11
    v11 --> v13
    v11 --> v12
    v13 --> v14
    v15 --> v17
    v16 --> v17
    v17 --> v21
    v17 --> v18
    v19 --> v21
    v20 --> v21
    v21 --> v23
    v21 --> v22
    v23 --> v25
    v23 --> v24
    v3 --> v26
    v26 --> v27
    v29 --> v30
    v27 --> v30
    v30 --> v31
    v30 --> v33
    v30 --> v41
    v30 --> v47
    v27 --> v36
    v33 --> v36
    v36 --> v37
    v37 --> v39
    v39 --> v40
    v39 --> v41
    v39 --> v47
    v41 --> v42
    v42 --> v43
    v42 --> v44
    v44 --> v46
    v47 --> v48
    v48 --> v49
    v54 --> v55
    v47 --> v55
    v55 --> v56
    v55 --> v57
    v57 --> v61
    v61 --> v62
