flowchart TB
    subgraph " "
    v0["csv_file"]
    v3["min_sequence_length"]
    v14["checked_clusters"]
    v15["minimum_members"]
    v16["num_cluster_chunks"]
    v22["dir_name"]
    v35["informat"]
    v36["outformat"]
    v60["informat"]
    v61["outformat"]
    v65["informat"]
    v66["outformat"]
    v71["informat"]
    v72["outformat"]
    v75["hmm_db"]
    v76["db_name"]
    v85["compute_mode"]
    v99[" "]
    end
    subgraph PREPROCESS_INPUT
    v1([REMOVE_HEADER])
    v2(( ))
    end
    subgraph INITIATE_PROTEINS
    v4([FILTER_UNANNOTATED_SLICES])
    v5(( ))
    end
    subgraph EXECUTE_CLUSTERING
    v7([MMSEQS_CREATEDB])
    v9([MMSEQS_LINCLUST])
    v11([EXPORT_CLUSTERS_TSV])
    v13(( ))
    end
    subgraph " "
    v8[" "]
    v10[" "]
    v12["num_sequences"]
    v38[" "]
    v41[" "]
    v44[" "]
    v49["id_mapping"]
    v50["metadata"]
    v51["converged"]
    v52["successful"]
    v53["discarded"]
    v54["tsv"]
    v55["domtblout"]
    v56["rf"]
    v57["hmm"]
    v63[" "]
    v68[" "]
    v70["fa_ch"]
    v74[" "]
    v78[" "]
    v80[" "]
    v81[" "]
    v87[" "]
    v89[" "]
    v92[" "]
    v94[" "]
    v101[" "]
    v107[" "]
    end
    subgraph GENERATE_FAMILIES_PARALLEL
    v17([CHUNK_CLUSTERS])
    v20([REFINE_FAMILIES_PARALLEL])
    v18(( ))
    v21(( ))
    v25(( ))
    v26(( ))
    v27(( ))
    v28(( ))
    v29(( ))
    v30(( ))
    v31(( ))
    v32(( ))
    v33(( ))
    v34(( ))
    end
    v23([MOVE_TO_DIR])
    subgraph REMOVE_REDUNDANCY
    v37([HHSUITE_REFORMAT])
    v40([HHSUITE_BUILDHHDB])
    v43([HHSUITE_HHBLITS])
    v45([COMBINE_HH_RESULTS])
    v46([MAP_FIRST_A3M_SEQUENCES_TO_FAMILY_ID])
    v47([REMOVE_REDUNDANT])
    v48([POOL_FAMILY_RESULTS])
    v39(( ))
    v42(( ))
    v58(( ))
    v59(( ))
    end
    subgraph REFORMAT_SEED_MSA
    v62([HHSUITE_REFORMAT])
    v64([TRANSLATE_MSA_MGYPS])
    end
    subgraph REFORMAT_HMMALIGN_MSA
    v67([HHSUITE_REFORMAT])
    v69([TRANSLATE_MSA_MGYPS])
    end
    subgraph ANNOTATE_MODELS
    v73([HHSUITE_REFORMAT])
    v77([HHSUITE_HHBLITS])
    v79([FILTER_HH_RESULTS])
    end
    subgraph PREDICT_STRUCTURES
    v82([EXTRACT_FIRST_STOCKHOLM_SEQUENCES])
    v86([ESMFOLD])
    v88([EXTRACT_ESMFOLD_SCORES])
    v93([PARSE_CIF])
    v83(( ))
    v90(( ))
    end
    subgraph ANNOTATE_STRUCTURES
    v100([FOLDSEEK_EASYSEARCH_PDB])
    v106([FIND_ANNOTATED_FAMILIES_BY_STRUCTURE])
    v102(( ))
    end
    v24(( ))
    v0 --> v1
    v1 --> v2
    v3 --> v4
    v2 --> v4
    v4 --> v5
    v5 --> v7
    v7 --> v9
    v7 --> v8
    v7 --> v11
    v9 --> v11
    v9 --> v10
    v11 --> v12
    v11 --> v13
    v14 --> v17
    v15 --> v17
    v16 --> v17
    v13 --> v17
    v17 --> v18
    v5 --> v20
    v18 --> v20
    v20 --> v21
    v20 --> v25
    v20 --> v26
    v20 --> v27
    v20 --> v28
    v20 --> v29
    v20 --> v30
    v20 --> v31
    v20 --> v32
    v20 --> v33
    v20 --> v34
    v22 --> v23
    v21 --> v23
    v23 --> v24
    v35 --> v37
    v36 --> v37
    v24 --> v37
    v37 --> v38
    v37 --> v40
    v37 --> v43
    v37 --> v46
    v37 --> v39
    v40 --> v41
    v40 --> v42
    v39 --> v43
    v42 --> v43
    v43 --> v45
    v43 --> v44
    v45 --> v47
    v46 --> v47
    v47 --> v48
    v21 --> v48
    v25 --> v48
    v26 --> v48
    v27 --> v48
    v28 --> v48
    v29 --> v48
    v30 --> v48
    v31 --> v48
    v32 --> v48
    v33 --> v48
    v34 --> v48
    v48 --> v57
    v48 --> v56
    v48 --> v55
    v48 --> v54
    v48 --> v53
    v48 --> v52
    v48 --> v51
    v48 --> v50
    v48 --> v49
    v48 --> v58
    v48 --> v59
    v60 --> v62
    v61 --> v62
    v58 --> v62
    v62 --> v64
    v62 --> v63
    v64 --> v73
    v65 --> v67
    v66 --> v67
    v59 --> v67
    v67 --> v69
    v67 --> v68
    v69 --> v70
    v71 --> v73
    v72 --> v73
    v73 --> v77
    v73 --> v74
    v75 --> v77
    v76 --> v77
    v77 --> v79
    v77 --> v78
    v79 --> v81
    v79 --> v80
    v59 --> v82
    v82 --> v83
    v85 --> v86
    v83 --> v86
    v86 --> v93
    v86 --> v88
    v86 --> v87
    v86 --> v100
    v88 --> v89
    v88 --> v90
    v90 --> v92
    v93 --> v94
    v99 --> v100
    v100 --> v101
    v100 --> v102
    v102 --> v106
    v106 --> v107
