flowchart TB
    subgraph " "
    v0["clusters"]
    v1["checked_clusters"]
    v2["minimum_members"]
    v3["num_cluster_chunks"]
    v6["mgnifams_fasta"]
    v17["fraction"]
    v20["dir_name"]
    v32["informat"]
    v33["outformat"]
    end
    subgraph GENERATE_FAMILIES_PARALLEL
    v4([CHUNK_CLUSTERS])
    v7([REFINE_FAMILIES_PARALLEL])
    v5(( ))
    v8(( ))
    v19(( ))
    v23(( ))
    v24(( ))
    v25(( ))
    v26(( ))
    v27(( ))
    v28(( ))
    v29(( ))
    v30(( ))
    v31(( ))
    end
    subgraph FLAG_TRANSMEMBRANE
    v10([EXTRACT_FIRST_STOCKHOLM_SEQUENCES])
    v11([DEEPTMHMM])
    v18([FLAG_TM])
    end
    subgraph " "
    v12[" "]
    v13[" "]
    v14[" "]
    v15[" "]
    v16[" "]
    v35[" "]
    v38[" "]
    v41[" "]
    v47[" "]
    v48[" "]
    v50["id_mapping"]
    v51["metadata"]
    v52["converged"]
    v53["successful"]
    v54["discarded"]
    v55["tsv"]
    v56["domtblout"]
    v57["rf"]
    v58["hmm"]
    v59["msa_sto"]
    v60["seed_msa_sto"]
    end
    v21([MOVE_TO_DIR])
    subgraph REMOVE_REDUNDANCY
    v34([HHSUITE_REFORMAT])
    v37([HHSUITE_BUILDHHDB])
    v40([HHSUITE_HHBLITS])
    v42([COMBINE_HH_RESULTS])
    v43([MAP_FIRST_A3M_SEQUENCES_TO_FAMILY_ID])
    v45([POOL_FAM_PROTEINS])
    v46([REMOVE_REDUNDANT_AND_TM])
    v49([POOL_FAMILY_RESULTS])
    v36(( ))
    v39(( ))
    end
    v22(( ))
    v0 --> v4
    v1 --> v4
    v2 --> v4
    v3 --> v4
    v4 --> v5
    v6 --> v7
    v5 --> v7
    v7 --> v8
    v7 --> v19
    v7 --> v23
    v7 --> v24
    v7 --> v25
    v7 --> v26
    v7 --> v27
    v7 --> v28
    v7 --> v29
    v7 --> v30
    v7 --> v31
    v8 --> v10
    v10 --> v11
    v10 --> v46
    v11 --> v18
    v11 --> v16
    v11 --> v15
    v11 --> v14
    v11 --> v13
    v11 --> v12
    v17 --> v18
    v18 --> v46
    v20 --> v21
    v19 --> v21
    v21 --> v22
    v32 --> v34
    v33 --> v34
    v22 --> v34
    v34 --> v35
    v34 --> v37
    v34 --> v40
    v34 --> v43
    v34 --> v36
    v37 --> v38
    v37 --> v39
    v36 --> v40
    v39 --> v40
    v40 --> v42
    v40 --> v41
    v42 --> v46
    v43 --> v46
    v26 --> v45
    v45 --> v46
    v46 --> v49
    v46 --> v48
    v46 --> v47
    v8 --> v49
    v19 --> v49
    v23 --> v49
    v24 --> v49
    v25 --> v49
    v26 --> v49
    v27 --> v49
    v28 --> v49
    v29 --> v49
    v30 --> v49
    v31 --> v49
    v49 --> v60
    v49 --> v59
    v49 --> v58
    v49 --> v57
    v49 --> v56
    v49 --> v55
    v49 --> v54
    v49 --> v53
    v49 --> v52
    v49 --> v51
    v49 --> v50
