flowchart TB
    subgraph " "
    v0["csv_file"]
    v3["min_sequence_length"]
    v15["starting_num_sequences"]
    v16["minimum_members"]
    v17["iteration"]
    v29["informat"]
    v30["outformat"]
    v34["informat"]
    v35["outformat"]
    v40["informat"]
    v41["outformat"]
    v44["hmm_db"]
    v45["db_name"]
    v54["compute_mode"]
    v68[" "]
    v77["out_dir"]
    v80["config_file"]
    end
    subgraph PREPROCESS_INPUT
    v1([REMOVE_HEADER])
    v2(( ))
    end
    subgraph INITIATE_PROTEINS
    v4([FILTER_UNANNOTATED_SLICES])
    v5(( ))
    end
    subgraph EXECUTE_CLUSTERING
    v7([MMSEQS_CREATEDB])
    v9([MMSEQS_LINCLUST])
    v11([EXPORT_CLUSTERS_TSV])
    v12(( ))
    end
    subgraph " "
    v8[" "]
    v10[" "]
    v14[" "]
    v19[" "]
    v20[" "]
    v21[" "]
    v22[" "]
    v23[" "]
    v24["domtblout"]
    v25[" "]
    v26["hmm"]
    v32[" "]
    v37[" "]
    v39["fa_ch"]
    v43[" "]
    v47[" "]
    v49[" "]
    v50[" "]
    v56[" "]
    v58[" "]
    v61[" "]
    v63[" "]
    v70[" "]
    v76[" "]
    v79[" "]
    v83[" "]
    v85[" "]
    end
    subgraph GENERATE_FAMILIES
    v13([CREATE_CLUSTERS_PKL])
    v18([REFINE_FAMILIES])
    v27(( ))
    v28(( ))
    end
    subgraph REFORMAT_SEED_MSA
    v31([HHSUITE_REFORMAT])
    v33([TRANSLATE_MSA_MGYPS])
    end
    subgraph REFORMAT_HMMALIGN_MSA
    v36([HHSUITE_REFORMAT])
    v38([TRANSLATE_MSA_MGYPS])
    end
    subgraph ANNOTATE_MODELS
    v42([HHSUITE_REFORMAT])
    v46([HHSUITE_HHBLITS])
    v48([FILTER_HH_RESULTS])
    end
    subgraph PREDICT_STRUCTURES
    v51([EXTRACT_FIRST_STOCKHOLM_SEQUENCES])
    v55([ESMFOLD])
    v57([EXTRACT_ESMFOLD_SCORES])
    v62([PARSE_CIF])
    v52(( ))
    v59(( ))
    end
    subgraph ANNOTATE_STRUCTURES
    v69([FOLDSEEK_EASYSEARCH_PDB])
    v75([FIND_ANNOTATED_FAMILIES_BY_STRUCTURE])
    v71(( ))
    end
    v78([EXPORT_MGNIFAMS_CSV])
    v81([QUERY_MGNPROTEIN_DB])
    v82([PARSE_BIOMES])
    v84([PARSE_DOMAINS])
    v0 --> v1
    v1 --> v2
    v3 --> v4
    v2 --> v4
    v4 --> v5
    v5 --> v7
    v7 --> v9
    v7 --> v8
    v7 --> v11
    v9 --> v11
    v9 --> v10
    v11 --> v12
    v12 --> v13
    v13 --> v18
    v13 --> v14
    v15 --> v18
    v16 --> v18
    v17 --> v18
    v5 --> v18
    v18 --> v26
    v18 --> v25
    v18 --> v24
    v18 --> v81
    v18 --> v23
    v18 --> v22
    v18 --> v21
    v18 --> v20
    v18 --> v19
    v18 --> v84
    v18 --> v27
    v18 --> v28
    v29 --> v31
    v30 --> v31
    v27 --> v31
    v31 --> v33
    v31 --> v32
    v33 --> v42
    v34 --> v36
    v35 --> v36
    v28 --> v36
    v36 --> v38
    v36 --> v37
    v38 --> v39
    v40 --> v42
    v41 --> v42
    v42 --> v46
    v42 --> v43
    v44 --> v46
    v45 --> v46
    v46 --> v48
    v46 --> v47
    v48 --> v50
    v48 --> v49
    v28 --> v51
    v51 --> v52
    v54 --> v55
    v52 --> v55
    v55 --> v62
    v55 --> v57
    v55 --> v56
    v55 --> v69
    v57 --> v58
    v57 --> v59
    v59 --> v61
    v62 --> v63
    v68 --> v69
    v69 --> v70
    v69 --> v71
    v71 --> v75
    v75 --> v76
    v77 --> v78
    v78 --> v79
    v80 --> v81
    v81 --> v82
    v81 --> v84
    v82 --> v83
    v84 --> v85
