flowchart TD
    p0((Channel.fromPath))
    p1[initiate_proteins:KEEP_UNANNOTATED]
    style p1 fill:#eae3b3
    p2[initiate_proteins:EXPORT_PROTEINS_CSV]
    style p2 fill:#baf8b1
    p3(( ))
    p4[execute_clustering:CREATEDB]
    style p4 fill:#f5c158
    p5[execute_clustering:LINCLUST]
    style p5 fill:#f5c158
    p6[execute_clustering:CREATETSV]
    style p6 fill:#f5c158
    p7[execute_clustering:EXPORT_CLUSTERING_CSV]
    style p7 fill:#baf8b1
    p8(( ))
    p9[create_families:PARSE_FAMILIES]
    style p9 fill:#ff8585
    p10(( ))
    p11[produce_models:MAFFT]
    style p11 fill:#c8c8c8
    p12[produce_models:HMMBUILD]
    style p12 fill:#c8c8c8
    p13(( ))
    p14((Channel.fromPath))
    p15((Channel.fromPath))
    p16((Channel.fromPath))
    p17((Channel.fromPath))
    p18([splitFasta])
    p19[annotate_slices:INTERPROSCAN]
    style p19 fill:#9cccff
    p20([collectFile])
    p21([first])
    p22([first])
    p23([first])
    p24[annotate_slices:EGGNOG_MAPPER]
    style p24 fill:#9cccff
    p25([collectFile])
    p26[annotate_slices:MAKEBLASTDB]
    style p26 fill:#9cccff
    p27([first])
    p28[annotate_slices:BLASTP]
    style p28 fill:#9cccff
    p29([collectFile])
    p30[annotate_slices:EXPORT_INTERPRO_ANNOTATIONS_CSV]
    style p30 fill:#baf8b1
    p31[annotate_slices:EXPORT_EGGNOG_ANNOTATIONS_CSV]
    style p31 fill:#baf8b1
    p32[annotate_slices:EXPORT_BLASTP_ANNOTATIONS_CSV]
    style p32 fill:#baf8b1
    p33([concat])
    p34([collect])
    p35(( ))
    p36[annotate_slices:CONCAT_ANNOTATIONS]
    style p36 fill:#baf8b1
    p37[FIND_UNANNOTATED_IDS]
    style p37 fill:#eae3b3
    p38(( ))
    p0 -->|mgy90_file| p1
    p1 -->|fastaFile| p2
    p2 --> p3
    p1 -->|fastaFile| p4
    p4 --> p5
    p5 --> p6
    p4 -->|mmseqs_DB| p6
    p6 -->|clust_tsv| p7
    p7 --> p8
    p1 -->|fastaFile| p9
    p6 -->|clust_tsv| p9
    p9 -->|reps_ids| p37
    p9 -->|fasta_ch| p18
    p9 -->|singleton_ids| p10
    p9 -->|familyFile| p11
    p11 --> p12
    p12 --> p13
    p14 -->|ch_eggnong_data_dir| p21
    p15 -->|ch_eggnog_diamond_db| p22
    p16 -->|ch_eggnog_db| p23
    p17 -->|uniprot_sprot_fasta_file| p26
    p18 -->|fasta_chunks_ch| p19
    p19 --> p20
    p20 -->|interpro_ch| p30
    p21 --> p24
    p22 --> p24
    p23 --> p24
    p18 -->|fasta_chunks_ch| p24
    p24 --> p25
    p25 -->|eggnog_ch| p31
    p26 --> p27
    p27 --> p28
    p18 -->|fasta_chunks_ch| p28
    p28 --> p29
    p29 -->|blastp_ch| p32
    p30 --> p33
    p31 --> p33
    p32 --> p33
    p33 --> p34
    p34 --> p36
    p35 -->|mode| p36
    p36 --> p37
    p37 --> p38
