---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/yaml-schema.json
name: "hhsuite_hhblits"
description: search an HHsuite database with a query sequence or MSA
keywords:
  - HMM
  - search
  - comparison
  - MSA
tools:
  - "hhsuite":
      description: "HH-suite3 for fast remote homology detection and deep protein annotation"
      homepage: "https://github.com/soedinglab/hh-suite"
      documentation: "https://github.com/soedinglab/hh-suite/wiki"
      tool_dev_url: "https://github.com/soedinglab/hh-suite"
      doi: "10.1371/journal.pone.0082138"
      licence: ["GPL v3"]
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - fa:
      type: file
      description: Input multiple sequence alignment file
      pattern: "*.{fa,fasta,fas,a2m,a3m,sto,psi,clu}"
  - informat:
      type: string
      description: Format of the input multiple sequence alignment file
      pattern: "fas|a2m|a3m|sto|psi|clu"
  - outformat:
      type: string
      description: Format of the output multiple sequence alignment file
      pattern: "fas|a2m|a3m|sto|psi|clu"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. `[ id:'test', single_end:false ]`
  - fa:
      type: file
      description: Transformed output multiple sequence alignment file
      pattern: "*.{fas,a2m,a3m,sto,psi,clu}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@vagkaratzas"
